### ISSUE TITLE
use puppet::module::modulepath parameter to assert the 'default' basemodulepath

### ISSUE THREAD

**Issue by wolfspyre** [abstractitptyltd/abstractit-puppet#10]
in puppet::master:

class puppet::master (
   #...
  $modulepath = '',
  #...
  $pre_module_path = '',
){
  #...
    $pre_module_path_real = $pre_module_path ? {
    ''       => '',
    /\w+\:$/ => $pre_module_path,
    default  => "${pre_module_path}:"
  }
  $extra_module_path    = $module_path ? {
    ''      => "${pre_module_path_real}${::settings::confdir}/site:/usr/share/puppet/modules",
    default => "${pre_module_path_real}${module_path}",
  }
  #...
}

This assumes that one will, by default, want things stored in ${::settings::confdir}/site and in /usr/share/puppet/modules.

That's as fine an assertion as any, But why bother with the extra logic? Just set the default value of $module_path to '${::settings::confdir}/site:/usr/share/puppet/modules' . This gives you your default values still, but removes some of the complication of having three sources for the path. you'd just concatenate pre_module_path_real with module_path and call it a day.

Thoughts?

**Comment by rendhalver** [comment]
I will be deprecating the old module_path and pre_module_path variables in favour of environmentpath and basemodulepath in 2.0.0

**Comment by rendhalver** [comment]
Fixed this with PR #43.
