### ISSUE TITLE
$::puppet::agent_cron_min_interpolated not always defined

### ISSUE THREAD

**Issue by chrisowensboston** [abstractitptyltd/abstractit-puppet#115]
The 'cron' entry in manifests/agent.pp references two variables $::puppet::agent_cron_min_interpolated and $::puppet::agent_cron_hour_interpolated (Lines 45 and 46) that are not always defined. See  init.pp line 149... they are only defined if $enable_mechanism == 'cron'

When I run spec tests on my own module that includes abstractit-puppet, the compiler doesn't like this, since I run in strict mode.

**Comment by rendhalver** [comment]
I am very willing to accept a PR to fix this.

**Comment by chrisowensboston** [comment]
I can’t get the spec tests to run, probably because I have the wrong version of Ruby configured. Gimme a hint? As soon as I sort that I’ll send a pull request.

**Comment by chrisowensboston** [comment]
The version obtained from forge and the production branch on github both say version 2.2.1 in metadata.json.... but the version from forge has all the files dated Feb 11 2016 (and has this problem) while the production branch on github has last commit July 26, 2016 and does not have the problem.

**Comment by rendhalver** [comment]
I have been updating the version when I do a new release so that would be why the version is the same.
I do need to make a new release when I get a chance.

**Comment by chrisowensboston** [comment]
I'm closing this issue since the problem is fixed in the production branch on github
