### ISSUE TITLE
module keeps reinstalling 'puppet' and 'facter' packages

### ISSUE THREAD

**Issue by seanscottking** [abstractitptyltd/abstractit-puppet#119]
Thanks for this awesome module. I just started using it to provision a v4 puppetmaster setup. I'm working on vagrant with centos/7 box, and I'm seeing this on every puppet run:

```
==> default: Notice: /Stage[main]/Puppet::Install::Deps/Package[facter]/ensure: created
==> default: Notice: /Stage[main]/Puppet::Install/Package[puppet]/ensure: created
```

I didn't look yet but it's almost certainly caused by the fact that both of these package link to `puppet-agent` package in the v4 puppetlabs repository. Therefore, doing `package { 'facter': ensure => present, }` will successfully install `puppet-agent` package and satisfy puppet, but on the next run puppet won't see `facter` in the package list and therefore attempt to reinstall each time. I'll take a closer look and send a PR unless someone beats me to it.

**Comment by rendhalver** [comment]
So you have $::puppet::allinone set to true?
If you don't it will be trying to manage the old packages.

**Comment by seanscottking** [comment]
I started off sparingly and did not set `$::puppet::allinone` to `true` and it defaults to `false`. I see "_allinone_" is a new Puppet Labs term, as is "_Puppet Collection_," so I have some further reading to do.

Not sure if this issue should be attributed to my v4 noobness or not.

**Comment by rendhalver** [comment]
Maybe my docs aren't specific enough.
The default support for the module is pre puppet 4 so I don't clobber people who haven't upgraded yet.
It's an opt in feature.
Once you set it up it will work like it should with puppet 4.
If it doesn't let me know. :)

**Comment by seanscottking** [comment]
I'm going to close this, the suggestion to set `$::puppet::allinone` to `true` worked for me. I agree with you, this might be a doc issue for folks getting started with your module. Let me know if you need help, I can submit a PR to the README.

**Comment by rendhalver** [comment]
Yeah I can see the confusion.
The docs aren't very specific.
Open up an issue so we can track it.
Thanks for the input.
