### ISSUE TITLE
We should allow basic autosigning.

### ISSUE THREAD

**Issue by wolfspyre** [abstractitptyltd/abstractit-puppet#12]
http://docs.puppetlabs.com/puppet/latest/reference/ssl_autosign.html

we should facilitate populating autosign.conf with a list of supported domains/fqdns. and informing puppet of its' location.

I'm on the fence about tooling for policy based autosigning. I think it's a good idea in general, but not something I'm chomping at the bit to implement now.

**Comment by rendhalver** [comment]
Fixed in 2.1.0
