### ISSUE TITLE
autosign.conf file owner 'root' affects puppetserver running as 'puppet'

### ISSUE THREAD

**Issue by explosivose** [abstractitptyltd/abstractit-puppet#146]
When my autosign.conf file is provisioned the owner is 'root'. For a while it confused me that this was being ignored until I noticed puppetserver is running as 'puppet' user. After I chown'd the autosign.conf file to puppet:puppet, autosign began working as expected

Running Centos 7 in a VM

https://github.com/abstractitptyltd/abstractit-puppet/blob/production/manifests/master/config.pp

**Comment by rendhalver** [comment]
The puppet user should be able to read that file.
What error messages are you seeing?

**Comment by explosivose** [comment]
We can close this issue, I can't replicate it anymore, so I think I must have made a mistake somewhere on that day
