### ISSUE TITLE
Upgrading to puppet 4 (PC1) from 3.8 sets incorrect default paths

### ISSUE THREAD

**Issue by hrpatel** [abstractitptyltd/abstractit-puppet#158]
I'm trying to run the following code using puppet 3.8.7 to upgrade puppet to v4
```ruby
    # upgrade to puppet v4
    class { '::puppet::profile::agent':
      allinone                  => true,
      collection                => 'PC1',
      enabled                   => false,
      manage_etc_facter         => false,
      manage_etc_facter_facts_d => false,
      reports                   => false,
      show_diff                 => true
    }
```

However, `/etc/puppet/puppet.conf` is modified instead of `/etc/puppetlabs/puppet/puppet.conf` when `Class['puppet::config']` is applied. Is this by design? If so, why?

I believe this statement in `puppet::defaults` should account for upgrading from 3 to 4 and not just `$::puppetversion`
```ruby
  if ( versioncmp($::puppetversion, '4.0.0') >= 0 ) {
    ...
```

**Comment by rendhalver** [comment]
You have discovered an edge case that I had not thought of.
The check is based on the currently installed version.
So I guess that is by design.
If we switched that check to use the allinone variable instead that would apply the config setting to the right file.
I will see about getting that fixed.
If you want to have a go at it I am happy to accept PR's

**Comment by hrpatel** [comment]
Thanks for the quick reply.. 

I had a similar thought about using `$allinone` and updating that line to this (keep `$::puppetversion` for clarity):
```ruby
  # if we are currently running puppet v4 or upgrading to it
  if versioncmp($::puppetversion, '4.0.0') >= 0 or $puppet::allinone {
    ...
```

Let me know your thoughts. If this works, I will send you a PR.

**Comment by rendhalver** [comment]
I like that option.

**Comment by hrpatel** [comment]
Change works as expected..

```ini
cat /etc/puppetlabs/puppet/puppet.conf

# This file can be used to override the default puppet settings.
# See the following links for more details on what settings are available:
# - https://docs.puppetlabs.com/puppet/latest/reference/config_important_settings.html
# - https://docs.puppetlabs.com/puppet/latest/reference/config_about_settings.html
# - https://docs.puppetlabs.com/puppet/latest/reference/config_file_main.html
# - https://docs.puppetlabs.com/puppet/latest/reference/configuration.html

[agent]
show_diff = true
runinterval = 30m
preferred_serialization_format = pson
reports = false
environment = production
splay = false

[main]
cfacter = false
server = puppet
stringify_facts = true
```

**Comment by hrpatel** [comment]
@rendhalver the PR requires a reviewer - can you do this or do I need to find someone? Just wondering about the process..

**Comment by rendhalver** [comment]
Thanks for that. I will take a look.

**Comment by rendhalver** [comment]
Welcome to the Contributor list @hrpatel!

**Comment by hrpatel** [comment]
Thanks @rendhalver! 😃 
Is it on me to close the issue?

**Comment by hrpatel** [comment]
Also, I currently get the module using this URL: https://forge.puppet.com/v3/files/abstractit-puppet-2.4.0.tar.gz

How often are the forge files updated?

**Comment by rendhalver** [comment]
Whenever I push out a new release.
I will publish a new bug fix release as soon as I get a chance.

**Comment by hrpatel** [comment]
Sounds good. 
Do I have to close this Issue?

**Comment by rendhalver** [comment]
It's technically fixed so go ahead.
