### ISSUE TITLE
split module?

### ISSUE THREAD

**Issue by toepi** [abstractitptyltd/abstractit-puppet#51]
I have found your module and am impressed how many features it has.

But you manage "to much" in own module which prevent me to use your module. Create dependency cycles why I use some modules in newer version (puppetdb).

Why not split out the modules into 3 parts:

one for agent (::puppet)
one for master (depends on agent ::puppet:master)
and one for the profiles (depends on master, agent, puppetdb and so one)

What do you think about it?

**Comment by rendhalver** [comment]
Hi.

Is your module published anywhere so I can have a look at the code?

I believe the module in it's current state can do what you need without splitting it up.
The base class can be used independently of the master class, setting up puppetdb is optional and managed with the puppetlabs-puppetdb class so it's mostly just a wrapper.

The profiles are completely optional and don't get used unless you declare them so I don't see any benefit in having the code split across three modules when you can achieve what you are suggesting without it.

In the most recent release (here and on [https://forge.puppetlabs.com/abstractit/puppet](puppet forge) I have split most of the external functionality like puppetboard,puppetdb and R10k into profiles which again are completely optional.
In the base class for managing the agent and the puppet::master class I have done my best to make as much as possibly optional.

I manage the amount I do because in my setups I manage everything so in my opinion I don't manage enough.

**Comment by toepi** [comment]
thanks for your reply.

I've no module a site.pp and a Puppetfile and some profiles/roles only - currently in an not showable state (contains sensible data und so - but work for me).

Your are right, but currently you define all dependency in metadata.json so I can not put your module to my Puppetfile because it has a 'dependency cycle/issue' (not sure how to call it). In my eyes the issue are the profiles for puppetdb / puppetdashbord (not master and agent  - and this one I will use and have no module for my requirements).

Hope that i bring some light into my 'issue'. I like your code and think it is better to use it instead of copy some parts.

**Comment by rendhalver** [comment]
Yep I understand what you mean now.
You mentioned in your initial request that you use a newer version of the puppetdb module.
I do need to update my module to use a later version of puppetdb.
I will do my best to get that sorted out soon and let you know how it goes.

Would that help your situation?
Would you be willing to run it in your development environment and see if it fixes the issue?

**Comment by toepi** [comment]
Yes, I manage puppetdb with version 5.0 of the module.

If you update it, it would help, but is this the best solution?

I will try to test your module on my vagrant-dev-env, after updated dependency. 

Thanks for your support.

**Comment by rendhalver** [comment]
I will make a new branch and get that setup soon.
I will comment here and let you know when it's ready for testing.

Thanks for prompting me to get that updated :)

**Comment by rendhalver** [comment]
Hi @toepi,
I have just pushed up a new branch you can use for testing: [Issue_51](https://github.com/abstractitptyltd/abstractit-puppet/tree/Issue_51)
Here is is actual commit: * 7eeefe7
Spec test results are here if you want to have a look: [Build 274](https://travis-ci.org/abstractitptyltd/abstractitptyltd/abstractit-puppet/builds/87162158)

If you are not sure how to add this to your Puppetfile let me know.

Thanks again.

**Comment by toepi** [comment]
Thanks again,

"New issue", Use `puppetlabs-apt` Version `2.2.0` but your module define `> 1.8.0 and < 2.0.0` :(.

**Comment by toepi** [comment]
wrong button :(

**Comment by rendhalver** [comment]
Thanks for that. :)
I was wondering if apt might need an update as well.
I will push some updates for that into the Issue_51 branch as well and let you know when it's ready.

**Comment by rendhalver** [comment]
Hi again.
I remember why I was holding back updating apt to the 2.x series.
puppetlabs-postgresql didn't support it.
Lucking apt 2.1.x added compatibility  with the older parameters.

I just pushed up fixes for that which should pass all my CI tests.

Let me know how it goes.

**Comment by toepi** [comment]
Sry for the delay, had no access to my 'test-infrastructure'. Now I can include your nice module into my Puppetfile and librarian is able to download it. Thanks!

But I have some questions about your profiles / functions:

- `profile::puppetdb` configure puppetmaster also, this mean puppetdb and master must run at same node?
- `puppetdb::master::config` has a parameter `puppet_service_name` which is set to httpd in the case of passanger but httpd is red hat - but passenger only supported at ubuntu (readme) which called service apache2? Need more logic here?
- if msgpack is enable it will be included into puppet.conf, but it can not be revert, right? I thing setting must be included in both cases or must be absent if not msgpack.

What do you think about this points? Currently  I have no time to create pullrequest for it, sry!

Think this issue can be closed with a merge of your branch.

**Comment by rendhalver** [comment]
Thanks for letting me know that fixed your install issue.
I will get that merged soon.

Those are all very good points.
I am happy to work on those as well.

The puppetdb profile does configure puppetmaster as well so yes all on one node.
I was looking at that and I also think I should split it up.
Moving the parts that configure puppetdb on the puppetmaster into the master profile is the best idea I think.

If you open an issue for each point I will get them sorted out.

Thanks again for the feedback.

**Comment by toepi** [comment]
Thanks again, create 3 issues (53, 54 and 55). Hope they are so okay.

**Comment by rendhalver** [comment]
I saw those.
They explain the issues well so they are quite okay.

Thanks again.
I will get do my best to get those sorted out soon.
