### ISSUE TITLE
Error when stopping/starting puppet agent

### ISSUE THREAD

**Issue by TravellingGuy** [abstractitptyltd/abstractit-puppet#66]
There seems to be a small problem with the commit for issue #32.

By default, ini_setting will use a separator of ' = ', but it seems that (on Ubuntu 14.04 at least) the service command doesn't like the whitespace around the = and when you do a `service puppet stop` or `service puppet start`, it displays an error:
`/etc/init.d/puppet: 5: /etc/default/puppet: START: not found`

The fix for this is to add this to the 'puppet sysconfig start' ini_setting in manifests/agent.pp:
`key_val_separator  => '=',`

Sorry, I don't have a pull request, I hacked around the problem in my profile class instead of cloning your module. :-)

**Comment by rendhalver** [comment]
Thanks for letting me know.
I will get that fixed soon.

**Comment by rendhalver** [comment]
Sorry for the delay.
I am going to make a start on this now.

**Comment by rendhalver** [comment]
Actually if you have a fix there can you adjust the tests for that and submit a PR?
Thanks.

**Comment by TravellingGuy** [comment]
I've never delved into writing tests for puppet modules, so I'd have no idea what I would be doing in adjusting the tests for that, unfortunately. (I write perfect code. :smile: )

**Comment by rendhalver** [comment]
It's not that tricky.
This is the test that checks the code you have adjusted.
If it's not obvious let me know.

https://github.com/abstractitptyltd/abstractit-puppet/blob/production/spec/classes/puppet_agent_spec.rb#L246

**Comment by TravellingGuy** [comment]
Cool, I'll take a look. I want to start writing tests for my modules, so this will get my feet wet.

**Comment by rendhalver** [comment]
Good luck!
Let me know if you get stuck.

**Comment by rendhalver** [comment]
All fixed I believe.
Thanks again Todd. :)
