### ISSUE TITLE
Invalid parameter purgedirs on Class[R10k]

### ISSUE THREAD

**Issue by divansantana** [abstractitptyltd/abstractit-puppet#70]
Due to this commit in r10k module
https://github.com/acidprime/r10k/commit/30110d9d844c1c92dee26af4a1f8c0d6ebb4b00e
this module errors out with
````
Invalid parameter purgedirs on Class[R10k]  at /etc/puppet/modules/puppet/manifests/profile/r10k.pp:101
```
Seems that option is deprecated now.

**Comment by divansantana** [comment]
This commit should fix it though I haven't tested much.
https://github.com/divansantana/abstractit-puppet/commit/fa5e3465d8833f79f28c465ef239f37625d00e70

**Comment by rendhalver** [comment]
That does look like it will fix the problem.
Send me a PR.

**Comment by divansantana** [comment]
Cool, done. #72

**Comment by rendhalver** [comment]
For future reference please don't add changelog entries to your PR.
I add those when I do release so the dates and version numbers match.

**Comment by divansantana** [comment]
Noted.
