### ISSUE TITLE
Management of yumrepo

### ISSUE THREAD

**Issue by djjudas21** [abstractitptyltd/abstractit-puppet#73]
I think there's a bug in this module. I'm running puppet 3.8.4 on CentOS 7, not from Puppet Collections. Your module installs `puppetlabs-release` in `repo.pp` and then goes on to manage several `yumrepo` resources in `repo/yum.pp`. The end result is that on my system, in `/etc/yum.repos.d` I have one file `puppetlabs.repo` which contains all 6 repo definitions and also a set of 6 files named `puppetlabs-products.repo`, `puppetlabs-deps`, etc.

Unless I've missed something, I can't see the benefit of managing these pieces of config twice. It causes the following problems:

```
[jg4461@dhcp-p3 ~]$ yum repolist
Loaded plugins: fastestmirror, langpacks
Repository puppetlabs-products is listed more than once in the configuration
...
```

```
[jg4461@dhcp-p3 ~]$ sudo puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for dhcp-p3.isys.bris.ac.uk
Info: Applying configuration version '1453369477'
Error: Could not prefetch yumrepo provider 'inifile': Section "puppetlabs-products" is already defined, cannot redefine in /etc/yum.repos.d/puppetlabs-products.repo
...
```

The way I see it, there are 4 ways of fixing this:

1. Stop installing the `puppetlabs-release` package
2. Stop handling the `yumrepo` resources
3. Add `require => Package['puppetlabs-release']` to every `yumrepo` in the vain hope that it might install `puppetlabs-release` first and then use `yumrepo` to manage the contents of it without duplicating them.
4. Allow users to enable/disable management of the `puppetlabs-release` package and `yumrepo` resources by setting a parameter

I'm happy to fix the bug and send a PR but I want to know your preferred method before I start.

Cheers,
Jonathan

**Comment by rendhalver** [comment]
My assumption was that the puppetlabs-release package would already be installed on a system managed with puppet but I guess most systems have some version of puppet available so maybe isn't necessary.

There is a manage_repos parameter in the main puppet class if you set that to false it won't manage the yumrepo resources, that should help for now.

I will try out the require and see if that helps.

I will see if this happens on other versions of CentOS.

Thanks for letting me know.

**Comment by djjudas21** [comment]
For us, we use this module to install puppet on new build systems so they don't have any repos. In the meantime I'll try the `manage_repos` options - don't know why I didn't spot that before.

**Comment by rendhalver** [comment]
Nice to see it's getting lots of use. :)

I have been thinking of not managing the puppetlabs-release package so I might remove that now.

As you mention in another issue it is definitely time for a new release.

**Comment by rendhalver** [comment]
I am attempting to setup an extra variable to set which method to manage the repos with.
The branch Issue_73 is an attempt to fix this but some of it is not working.
I can't see anything wrong with my code or the tests and I have no idea why they are failing.
Can I get you to give my code a look and see if there are any obvious errors.
Thanks.

The travis build errors are here https://travis-ci.org/abstractitptyltd/abstractit-puppet/jobs/104795982#L1005

**Comment by rendhalver** [comment]
It looks like I have finally got this working.
I will make a new release soon.

**Comment by djjudas21** [comment]
Oh, nice one. Sorry I didn't get a chance to get back to you yesterday - my baby daughter has been in hospital. I'm back at work today - see if I get a chance to sneak your fixed code into my dev environment.

Cheers,
Jonathan

**Comment by rendhalver** [comment]
Supporting puppet 4 and 3 is getting a bit tricky but I managed to fix a few other long standing spec test issues so that was nice too.
Let me know how your testing goes.
I have one other see reported issue that someone else has a fix for so I have asked for a PR for that so when that is done I will push out a new release.

**Comment by rendhalver** [comment]
Just letting you know I pushed out a new release to puppet forge : https://forge.puppetlabs.com/abstractit/puppet
