### ISSUE TITLE
puppetdb 2.x fails to start with "Missing some SSL configuration"

### ISSUE THREAD

**Issue by divansantana** [abstractitptyltd/abstractit-puppet#84]
Trying to deploy puppetdb 2.x (puppet 3.x) with SSL is failing.

```puppet
    class { '::puppet::profile::agent': }
    class { '::puppet::profile::puppetdb': }
```

And hiera
```yaml
---
puppet::profile::puppetdb::puppetdb_version: '2.3.8-1puppetlabs1'
puppet::profile::puppetdb::use_ssl: true
puppet::profile::puppetdb::puppetdb_ssl_listen_address: '0.0.0.0'
puppet::ca_server: puppetca.example.co.za
```

When puppet apply works however puppetdb service fails to start with
```
2016-02-25 13:12:33,016 INFO  [p.t.s.w.jetty9-service] Starting web server(s).
2016-02-25 13:12:33,034 ERROR [p.t.internal] Error during service start!!!
java.lang.IllegalArgumentException: Missing some SSL configuration; must provide either :ssl-cert, :ssl-ke
y, and :ssl-ca-cert, OR :truststore, :trust-password, :keystore, and :key-password.
        at puppetlabs.trapperkeeper.services.webserver.jetty9_config$eval21641$get_jks_keystore_config_BANG___21642$fn__21646.invoke(jetty9_config.clj:288) ~[na:na]
```

Think the issue is that `ssl-key`, `ssl-cert` and `ssl-ca-cert` are not being set in `/etc/puppetdb/conf.d/jetty.ini`.

**Comment by rendhalver** [comment]
Awesome.
Thank you so much.

**Comment by rendhalver** [comment]
Not sure if you are aware of this have a look here for how to close issues when your PR get merged.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by divansantana** [comment]
Ah thanks - That's helpful. I'll do that next time. Just deployed gitlab internally too so that should help with learning these sort of things too.

PS. This issue (unresolved so far) is separate and almost opposite to the issue and PR I logged earlier.

**Comment by rendhalver** [comment]
Yep silly me.
I will have a look at this tomorrow.
I am not sure now much of the jetty.ini file the puppetdb module manages.

**Comment by divansantana** [comment]
I'm too sure how this should work. Or how this module should configure it.

puppetdb module can handle the SSL certs for you and configure in jetti.ini by changing this in `manifests/profile/puppetdb.pp`:
```puppet
  class { '::puppetdb':
    ...
    ssl_set_cert_paths => true,
    ssl_deploy_certs   => true,
    ...
  }
```

That sets the below in `jetty.ini`
```ini
ssl-key = /etc/puppetdb/ssl/private.pem
ssl-cert = /etc/puppetdb/ssl/public.pem
ssl-ca-cert = /etc/puppetdb/ssl/ca.pem
```
Though the pem files in `/etc/puppetdb/ssl` are empty.
I /think/ one would want them to be the same as the puppet agent certs of itself, typically (the puppetdb server). Therefore:
```bash
ln -s /etc/puppet/ssl/private_keys/cts-puppetdb.fnb.co.za.pem /etc/puppetdb/ssl/private.pem
ln -s /etc/puppet/ssl/certs/ca.pem /etc/puppetdb/ssl/ca.pem
ln -s /etc/puppet/ssl/public_keys/cts-puppetdb.fnb.co.za.pem /etc/puppetdb/ssl/public.pem
```

**Comment by rendhalver** [comment]
PuppetDB has always copied the ssl certs into that directory.
I have vague memories of it converting them into something Java could use so that is likely the reason for the extra directory. I think they are direct copies these days.
I would think PuppetDB should be copying the certs over on startup.

**Comment by divansantana** [comment]
I'll try look into this a bit more hopefully in the next few days.

**Comment by divansantana** [comment]
Ok finally gotten back to this...

Setting this in hiera yaml resolves the issue
```yaml
puppetdb::ssl_deploy_certs: true
```

This should be updated in the code.
