### ISSUE TITLE
$reports_dir default is incorrect for puppet 4.x

### ISSUE THREAD

**Issue by greenaar** [abstractitptyltd/abstractit-puppet#85]
For puppet 4.3 at least, reports_dir should be /opt/puppetlabs/server/data/puppetserver/reports

**Comment by rendhalver** [comment]
Thanks for that.
I will get that fixed.

**Comment by rendhalver** [comment]
The config variable is reportdir which according to the docs is $vardir/reports by default.
I will change my clean reports cron to use that variable instead of the reports_dir variable I set.

For reference.
https://docs.puppetlabs.com/puppet/latest/reference/configuration.html#reportdir
