### ISSUE TITLE
Could not find group puppet

### ISSUE THREAD

**Issue by jrevillard** [abstractitptyltd/abstractit-puppet#87]
Hi,

It seems that the puppet user/group is not available anymore since the migration to the puppet-agent package:

```
Error: Could not find group puppet
Error: /Stage[main]/Puppet/File[/opt/puppetlabs/facter]/group: change from root to puppet failed: Could not find group puppet
Notice: /Stage[main]/Puppet/File[/opt/puppetlabs/facter/facts.d]: Dependency File[/opt/puppetlabs/facter] has failures: true
Warning: /Stage[main]/Puppet/File[/opt/puppetlabs/facter/facts.d]: Skipping because of failed dependencies
```

```
 # rpm -qa puppet-agent
puppet-agent-1.4.2-1.el6.x86_64
```

The problem occurs on RedHat and Debian based OS.

Best,
Jerome

**Comment by rendhalver** [comment]
That seems a bit extreme. Do you know which user they use instead?

**Comment by jrevillard** [comment]
They do not create any user... everything is root...

Best,
Jerome

**Comment by seanscottking** [comment]
+1 on this issue, I'll be watching #114

**Comment by seanscottking** [comment]
Resolved by #132

**Comment by janorn** [comment]
I am a bit confused about this. If you examine the puppetserver rpm you will find this preinstall script. Puppet master has always been run as puppet. However the puppet agent has to be run as root to be able to make changes.

```
# Note: changes to this section of the spec may require synchronisation with the
# install.sh source based installation methodology.
#
# Add puppet group
getent group puppet > /dev/null || \
  groupadd -r puppet || :
# Add puppet user
if getent passwd puppet > /dev/null; then
  usermod --gid puppet --home /opt/puppetlabs/server/data/puppetserver \
  --comment "puppetserver daemon" puppet || :
else
  useradd -r --gid puppet --home /opt/puppetlabs/server/data/puppetserver --shell $(which nologin) \
    --comment "puppetserver daemon"  puppet || :
fi
```

**Comment by rendhalver** [comment]
How is that confusing?
The server can run as puppet because it is basically just a web service.
The agent used to run as puppet but I think it just had elevated privileges.
I guess they just decided to change that with Puppet 4 and just run it as root.
