### ISSUE TITLE
r10k manage_ruby_dependency error

### ISSUE THREAD

**Issue by divansantana** [abstractitptyltd/abstractit-puppet#90]
Hi,

Getting this error when trying to deploy a puppetserver using the module:

```
Error: validate_re(): input needs to be a String, not a FalseClass at /root/modules/r10k/manifests/init.pp:25 on node node.example.com
```

r10k module version I'm using is 2.8.4.

**Comment by rendhalver** [comment]
Is this option version specific?
The minimum version we support is 2.7.0.
If this option doesn't work with 2.7.0 we will need a work around or we need to increase the minimum version of r10k that is supported.

**Comment by divansantana** [comment]
@rendhalver Hmm it seems that even with 2.7.0 this was an issue according to line [23 and 24 here](https://github.com/acidprime/r10k/blob/v2.7.0/manifests/init.pp#L23)

**Comment by rendhalver** [comment]
Works for me then.
Thanks for checking.

**Comment by divansantana** [comment]
@rendhalver that was fast. Thanks :+1: :)

**Comment by rendhalver** [comment]
My phone tells me all the things. :)
